apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - capd-manager.yaml

  - core-components.yaml
  - bootstrap-components.yaml
  - control-plane-components.yaml


  - https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/v1.6.0/test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/v1.6.0/test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/v1.6.0/test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/v1.6.0/test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml

commonLabels:
  cluster.x-k8s.io/v1beta1: v1beta1